### PR TITLE
[ fix #273 ] Add more parenthesis in arguments of operators and sections

### LINKED ISSUE #273: `snd $` compiles incorrectly
There seems to be an issue when compiling the function application operator `$` together with `snd`:

The file

```agda
module Test where

open import Haskell.Prelude

test : Int × Int → Int
test = λ x → snd $ x

{-# COMPILE AGDA2HS test #-}
```

is compiled to 

```haskell
module Test where

test :: (Int, Int) -> Int
test = (\ r -> snd r $)
```

which is **not** valid Haskell.

Apparently, something went wrong with the fixity of `$` and the compilation of `snd` (Agda) to `\ r -> snd r` (Haskell). It appears to me that a parentheses are missing, a good compilation output would be

```haskell
test = ((\ r -> snd r) $)
```

Agda2hs version: `github:agda/agda2hs?ref=v1.2`

### PR DESCRIPTION
**Pull request by jespercockx**
Ideally, our pretty-printing library should insert parenthesis where needed. However, hs-src-exts does not insert adequate parenthesis for infix operators so we need to insert some by hand (see issues #54 and #273).

This also disables the printing of `_- u` as a right section `(- u)` in Haskell, as that would be interpreted as a negation instead.

### CODE REVIEW

File: src/Agda2Hs/Compile/Term.hs [hunk 1]
```diff
@@ -286,7 +286,9 @@ compileTerm v = do
         body <- compileTerm body
         return $ case body of
           Hs.InfixApp _ a op b
-            | a == hsx -> Hs.RightSection () op b -- System-inserted visible lambdas can only come from sections
+            | a == hsx
+            , pp op /= "-"             -- Jesper: no right section for minus, as Haskell parses this as negation!
+            -> Hs.RightSection () op b -- System-inserted visible lambdas can only come from sections
```
Comment (omelkonian) [inline src/Agda2Hs/Compile/Term.hs:291]: Introducing `\ section -> section - ...` is quite ugly; why not use a left section on [subtract = flip (-)](https://hackage.haskell.org/package/base-4.7.0.2/docs/Prelude.html#v:subtract) instead?
```hs
            | a == hsVar x
            -> if pp op == "-" then
                   -- no right section for minus, as Haskell parses this as negation!
                   Hs.LeftSection () (QConOp $ unQual "subtract") b 
                else
                   -- System-inserted visible lambdas can only come from sections
                   Hs.RightSection () op b
```

Minor comments:
1. No need for the intermediate variable `hsx`, just inline here
2. No need to mention the name of the person writing the comment :P

Comment (jespercockx) [reply src/Agda2Hs/Compile/Term.hs:291]: For this PR I wasn't really looking at whether the output is *pretty*, just whether it is *correct*. But I agree that your version is prettier.

The variable `hsx` was already there, I didn't want to touch it since it's unrelated to this PR.

Writing my name in comments is a habit I got from working on Agda itself where it seems to be standard practice. I personally quite like these little bits of personality in the codebase :)
